/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedInstallningarRouteImport } from './routes/_authenticated/installningar'

const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInstallningarRoute =
  AuthenticatedInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/api/chat': typeof ApiChatRoute
  '/share/$token': typeof ShareTokenRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/api/chat': typeof ApiChatRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/_authenticated/installningar': typeof AuthenticatedInstallningarRoute
  '/api/chat': typeof ApiChatRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/integritetspolicy'
    | '/installningar'
    | '/api/chat'
    | '/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/integritetspolicy'
    | '/installningar'
    | '/api/chat'
    | '/share/$token'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/integritetspolicy'
    | '/_authenticated/installningar'
    | '/api/chat'
    | '/share/$token'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  ApiChatRoute: typeof ApiChatRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/installningar': {
      id: '/_authenticated/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof AuthenticatedInstallningarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInstallningarRoute: typeof AuthenticatedInstallningarRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInstallningarRoute: AuthenticatedInstallningarRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  ApiChatRoute: ApiChatRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
